Adding support for writing BlobNode (imagery)
davidcaron/pye57 pull request #59
Opened 2024-04-28 12:03 UTC by joaori

When trying to clone an E57 file with images, I've realized a missing binding to support adding a BlobNode field to a StructureNode.

I've introduced a unit test file with an example of the clone process, in case you find it useful.

2024-05-02 07:43 UTC, dancergraham commented
I had a look at the test file - it seems to be an unmodified copy of the standard e57 test file. After the uv hack attempt I was a bit nervous about accepting a pull request containing anonymous blob data 😁

2024-05-02 08:08 UTC, dancergraham requested changes
Looks good, thank you very much - I have made a few comments and a small fix is needed on the imports

2024-05-02 08:08 UTC, dancergraham commented on tests/test_libe57.py
> +    if (isinstance(node, libe57.BlobNode)):
suggestion: change to `elif`

2024-05-02 08:08 UTC, dancergraham commented on tests/test_libe57.py
> +def copy_node(node, dest_image):
question: would it make sense to add this function to the main pye57 library? For instance in the utils namespace ?

2024-05-02 08:08 UTC, dancergraham commented on tests/test_libe57.py
> +    # From http://www.libe57.org/data.html
praise: nice to have the source mentioned here

2024-05-02 08:08 UTC, dancergraham commented on tests/test_libe57.py
> +    if (isinstance(node, libe57.BlobNode)):
suggestion: move above the container types with the other terminal nodes

2024-05-03 12:07 UTC, joaori commented on tests/test_libe57.py
> +    request.addfinalizer(lambda: delete_retry(path))
My bad, last minute change before I pushed the code. 😅

2024-05-03 13:59 UTC, merged